Feature/api key support
resource-watch/aqueduct-analysis-microservice pull request #94
Opened 2023-08-24 22:28 UTC by solomon-negusse

2023-08-25 16:13 UTC, solomon-negusse commented
Hi @carlosdelrealwri, we are adding API key support to all microservices in the Resource Watch infrastructure.  This PR adds that and upgrades dependencies mainly to enable this.

2023-08-29 08:56 UTC, tiagojsag requested changes
It seems like your IDE is applying some sort of global code auto-formatting, that makes the PR huge while it's functionally quite small. While I'm all for that, perhaps going forward you can create a PR with the code style changes alone, and a separate one with the functional changes, so it's easier to navigate.

There's also a docker-compose-gr.yml file that I dont know what's for, but needs to be either updated with the new env vars, or deleted altogether.

2023-08-29 08:56 UTC, tiagojsag commented on requirements_dev.txt
> +pytest
pin a version

2023-08-29 08:56 UTC, tiagojsag commented on requirements.txt
>  pytz
while you're at it, pin all of these too

2023-09-19 15:52 UTC, merged